import { Plant, Category, Direction, Element, Sunlight, SafetyStatus, GuideSection } from './types';

export const INITIAL_PLANTS: Plant[] = [
  {
    plant_id: 'p_avocado',
    order_index: 1,
    name_si: 'අලිගැටපේර',
    name_en: 'Avocado',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SOUTH, Direction.SW],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['ගුණදායක පලතුරු', 'සෙවණ ලබා දෙයි'],
    cautions: ['සතුන්ට විෂ සහිතයි (Toxic to pets)'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1kI0yhDZrPHs3SKDBgUkYe1g5v_yOjbNG',
      'https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?auto=format&fit=crop&q=80&w=1000'
    ],
    image_search_links: ['https://www.google.com/search?q=Avocado+tree'],
  },
  {
    plant_id: 'p_bael',
    order_index: 2,
    name_si: 'බෙලි',
    name_en: 'Bael Fruit',
    category: [Category.OUTDOOR, Category.FRUIT, Category.HERB],
    directions: [Direction.NW, Direction.NORTH],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['පූජනීය ශාකයකි', 'ඖෂධීය ගුණ වැඩියි', 'සිසිල් පානයකි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/12NzkQaLIE_tpEVhj9tIa-4jxMH6tFgvn',
      'https://images.unsplash.com/photo-1618451845701-a1895a940428?auto=format&fit=crop&q=80&w=1000'
    ],
    image_search_links: ['https://www.google.com/search?q=Bael+fruit+tree'],
  },
  {
    plant_id: 'p_bamboo',
    order_index: 3,
    name_si: 'වාසනාවන්ත උණ (Lucky Bamboo)',
    name_en: 'Lucky Bamboo',
    scientific_name: 'Dracaena sanderiana',
    category: [Category.INDOOR, Category.HERB],
    directions: [Direction.EAST, Direction.NE],
    element: Element.WATER,
    sunlight: Sunlight.LOW,
    benefits: ['වාසනාව ගෙන එයි', 'අඩු නඩත්තුව', 'වාතය පිරිසිදු කරයි'],
    cautions: ['සතුන්ට මඳක් විෂ සහිත විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1uqW-AKg4sFyDjFJ1qsg4ReCMnkLmxYZo',
      'https://lh3.googleusercontent.com/d/12Wyphj5QMHXzz9HzB7XR83M2iyiKTP3o'
    ],
    image_search_links: ['https://www.google.com/search?q=Dracaena+sanderiana+Lucky+Bamboo'],
  },
  {
    plant_id: 'p_breadfruit',
    order_index: 4,
    name_si: 'දෙල් (Breadfruit)',
    name_en: 'Breadfruit',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.WEST, Direction.SW],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['පෝෂ්‍යදායී ආහාරයකි', 'විශාල සෙවණක්'],
    cautions: ['වැටෙන ගෙඩි ගැන සැලකිලිමත් වන්න'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/13twl9oQbYLcTIpi73FQbfYiR3w45OeNb'
    ],
    image_search_links: ['https://www.google.com/search?q=Breadfruit+tree'],
  },
  {
    plant_id: 'p_bromeliad',
    order_index: 5,
    name_si: 'බ්‍රොමෙලියඩ් (Bromeliad)',
    name_en: 'Bromeliads',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.EAST, Direction.NORTH],
    element: Element.AIR,
    sunlight: Sunlight.MEDIUM,
    benefits: ['වර්ණවත් පෙනුම', 'රාත්‍රී කාලයේ ඔක්සිජන් පිට කරයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1hC_K6sxCcY05N_oiWU_LBPNS1BKoz9vV',
      'https://images.unsplash.com/photo-1596720426673-e47c417f46f3?auto=format&fit=crop&q=80&w=1000'
    ],
    image_search_links: ['https://www.google.com/search?q=Bromeliad+plant'],
  },
  {
    plant_id: 'p_boxwood',
    order_index: 6,
    name_si: 'බොක්ස්වුඩ් (Boxwood)',
    name_en: 'Boxwood Topiary',
    category: [Category.OUTDOOR],
    directions: [Direction.NW, Direction.WEST],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['වැටවල් සඳහා සුදුසුයි', 'අලංකාර හැඩයකට කපා ගත හැක'],
    cautions: ['ගෙඩි විෂ සහිතයි'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: true,
    image_links: [
      'https://lh3.googleusercontent.com/d/1wAmXNy6ulD-D3i6-miCoq0-rfK_p6xkN',
      'https://images.unsplash.com/photo-1508013861974-9f6347163865?auto=format&fit=crop&q=80&w=1000'
    ],
    image_search_links: ['https://www.google.com/search?q=Boxwood+Topiary'],
  },
  {
    plant_id: 'p_pothos',
    order_index: 7,
    name_si: 'මුදල් වැල් (Pothos)',
    name_en: 'Pothos / Money Plant',
    scientific_name: 'Epipremnum aureum',
    category: [Category.INDOOR],
    directions: [Direction.SE, Direction.EAST, Direction.NORTH],
    element: Element.FIRE,
    sunlight: Sunlight.LOW,
    benefits: ['ධනය සහ වාසනාව කැඳවයි', 'වාතය පිරිසිදු කරයි', 'නඩත්තුව ඉතා පහසුයි'],
    cautions: ['සතුන්ට සහ දරුවන්ට මඳක් විෂ සහිතයි'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: [
      'https://lh3.googleusercontent.com/d/1VnZbuspnLbTn2LfaBxNrXfgSJbery-jJ',
      'https://tohgarden.com/wp-content/uploads/2022/04/2.png'
    ],
    image_search_links: ['https://www.google.com/search?q=Epipremnum+aureum+Pothos&tbm=isch'],
  },
  {
    plant_id: 'p_anthurium',
    order_index: 8,
    name_si: 'ඇන්තුරියම් (Anthurium)',
    name_en: 'Anthurium',
    scientific_name: 'Anthurium andraeanum',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.WATER,
    sunlight: Sunlight.LOW,
    benefits: ['සෞභාග්‍යය සහ ආගන්තුක සත්කාරය සංකේතවත් කරයි', 'වාතය පිරිසිදු කිරීමේ විශේෂ හැකියාව', 'වසර පුරා මල් ලබා දෙයි'],
    cautions: ['දරුවන්ට සහ සුරතල් සතුන්ට විෂ සහිත විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: [
      'https://lh3.googleusercontent.com/d/10nxbLjbYqU90Y5nrYPOxx5LXt3p1oT6y'
    ],
    image_search_links: ['https://www.google.com/search?q=Anthurium+plant'],
  },
  {
    plant_id: 'p_areca_hedge',
    order_index: 9,
    name_si: 'අරිකා වැට (Areca Hedge)',
    name_en: 'Areca Hedge',
    category: [Category.OUTDOOR],
    directions: [Direction.WEST, Direction.NW],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['පෞද්ගලිකත්වය ලබා දෙන වැටක් ලෙස', 'අලංකාර පෙනුම', 'විෂ වායූන් පෙරීම'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1W2sRcYsRRPMGfuSJhjRywwmY-_jKQ9Ne',
      'https://lh3.googleusercontent.com/d/1FYD1fWbhbJTBc7SZTyHm7zgipfIewT8C'
    ],
    image_search_links: ['https://www.google.com/search?q=Areca+hedge+palm'],
  },
  {
    plant_id: 'p_banana',
    order_index: 10,
    name_si: 'කෙසෙල් (Banana)',
    name_en: 'Banana (Musa)',
    scientific_name: 'Musa acuminata',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SW, Direction.SOUTH],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['ස්ථාවරත්වය සහ වාසනාව ගෙනෙයි', 'පෝෂ්‍යදායී පලතුරු', 'ආගමික වතාවත් සඳහා අවශ්‍ය වේ'],
    cautions: ['අකුණු සර වැදීමේ අවදානමක් ඇති බැවින් නිවසට ඉතා සමීපව වැවීමෙන් වළකින්න'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1jNkfskVQOK6r1o4lya4ASAiZUnq7bmZY'
    ],
    image_search_links: ['https://www.google.com/search?q=Banana+tree+Vastu'],
  },
  {
    plant_id: 'p_begonia',
    order_index: 11,
    name_si: 'බිගෝනියා (Begonia)',
    name_en: 'Begonia',
    scientific_name: 'Begonia semperflorens',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.NORTH],
    element: Element.AIR,
    sunlight: Sunlight.LOW,
    benefits: ['ධනාත්මක ශක්තිය', 'වර්ණවත් පත්‍ර සහ මල්', 'අභ්‍යන්තර අලංකරණයට'],
    cautions: ['සුරතල් සතුන්ට (විශේෂයෙන් බල්ලන් සහ බළලුන්) විෂ සහිත විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: true,
    image_links: [
      'https://lh3.googleusercontent.com/d/10b2mv-76ndA6dhSb3m8dyU5yLgpbHD2Y'
    ],
    image_search_links: ['https://www.google.com/search?q=Begonia+plant'],
  },
  {
    plant_id: 'p_bilimb',
    order_index: 12,
    name_si: 'බිලිං (Bilimb)',
    name_en: 'Bilimb',
    scientific_name: 'Averrhoa bilimbi',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.WEST, Direction.NW],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['පෝෂ්‍යදායී පලතුරකි', 'අච්චාරු සහ ව්‍යංජන සඳහා යොදා ගනී', 'විවිධ ඖෂධීය ගුණ ඇත'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1cXoNFr91Lf9G7-QoCYwXnqOwrL0JeyNc'
    ],
    image_search_links: ['https://www.google.com/search?q=Averrhoa+bilimbi+tree'],
  },
  {
    plant_id: 'p_bottle_palm',
    order_index: 13,
    name_si: 'බෝතල් පාම් (Bottle Palm)',
    name_en: 'Bottle Palm',
    scientific_name: 'Hyophorbe lagenicaulis',
    category: [Category.OUTDOOR, Category.INDOOR],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['සුවිශේෂී බඳුන් හැඩැති කඳ', 'ලස්සන විසිතුරු ශාකයකි', 'ඉඩකඩ අඩු ස්ථාන සඳහා සුදුසුයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1mrZB1bZLoK-Ev8mMaobpS1JO3zcYbMTY'
    ],
    image_search_links: ['https://www.google.com/search?q=Bottle+Palm+Hyophorbe'],
  },
  {
    plant_id: 'p_bougainvillea',
    order_index: 14,
    name_si: 'බෝගන්විලා (Bougainvillea)',
    name_en: 'Bougainvillea',
    scientific_name: 'Bougainvillea spectabilis',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.SOUTH, Direction.SE],
    element: Element.FIRE,
    sunlight: Sunlight.FULL,
    benefits: ['වර්ණවත් මල් ලබා දෙයි', 'වැටවල් සහ ආරුක්කු සඳහා ඉතා සුදුසුයි', 'නියඟයට ඔරොත්තු දීමේ හැකියාව'],
    cautions: ['ශාකයේ කටු ඇති බැවින් ප්‍රවේශම් වන්න'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1gj_g2h8TtMtGn5gIgJwceyxcrqLfn854'
    ],
    image_search_links: ['https://www.google.com/search?q=Bougainvillea+plant'],
  },
  {
    plant_id: 'p_butterfly_pea',
    order_index: 15,
    name_si: 'නිල් කටරොලු (Butterfly Pea)',
    name_en: 'Butterfly Pea',
    scientific_name: 'Clitoria ternatea',
    category: [Category.OUTDOOR, Category.FLOWER, Category.HERB],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.WATER,
    sunlight: Sunlight.MEDIUM,
    benefits: ['පූජනීය ශාකයකි (විෂ්ණු කාන්ති)', 'ඖෂධීය පානයන් සෑදීමට යොදා ගනී (Blue Tea)', 'ස්නායු පද්ධතියට ගුණදායකයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1mDdRDapVyS3D7S46_T2zJGXH4lzzi7Za'
    ],
    image_search_links: ['https://www.google.com/search?q=Clitoria+ternatea+Butterfly+Pea'],
  },
  {
    plant_id: 'p_canna_lily',
    order_index: 16,
    name_si: 'කැනා ලිලී (Canna Lily)',
    name_en: 'Canna Lily',
    scientific_name: 'Canna indica',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.SOUTH, Direction.SE],
    element: Element.FIRE,
    sunlight: Sunlight.FULL,
    benefits: ['වර්ණවත් පත්‍ර සහ මල්', 'වේගයෙන් වර්ධනය වේ', 'නිවසේ ප්‍රාණවත් බව වැඩි කරයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1f1aEVlWV4m7KRnoG5r69-3hmh5hb4ACm',
      'https://lh3.googleusercontent.com/d/1AN_sg7gHfKCQpbCh2q6g-asj0Fb2x7vY'
    ],
    image_search_links: ['https://www.google.com/search?q=Canna+Lily+plant'],
  },
  {
    plant_id: 'p_cashew',
    order_index: 17,
    name_si: 'කජු (Cashew)',
    name_en: 'Cashew',
    scientific_name: 'Anacardium occidentale',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SW, Direction.SOUTH],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['පෝෂ්‍යදායී කජු සහ පලතුරු', 'හොඳ සෙවණක් ලබා දෙයි', 'ආර්ථික වටිනාකම'],
    cautions: ['පලතුරේ යුෂ සමට අහිතකර විය හැක'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/18re2FX4xngU486vOBzCz_nNLkmBhwso1'
    ],
    image_search_links: ['https://www.google.com/search?q=Cashew+tree'],
  },
  {
    plant_id: 'p_christmas_cactus',
    order_index: 18,
    name_si: 'ක්‍රිස්මස් කැක්ටස් (Christmas Cactus)',
    name_en: 'Christmas Cactus',
    scientific_name: 'Schlumbergera',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.NORTH],
    element: Element.AIR,
    sunlight: Sunlight.LOW,
    benefits: ['අලංකාර මල් පිපීම', 'රාත්‍රියේ ඔක්සිජන් පිට කරයි', 'ධනාත්මක ශක්තිය'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1rOQhw7ltYLl2y7q5WuniTjhEgpJeW49B'
    ],
    image_search_links: ['https://www.google.com/search?q=Christmas+Cactus+plant'],
  },
  {
    plant_id: 'p_chrysanthemum',
    order_index: 19,
    name_si: 'සෙවන්ති (Chrysanthemum)',
    name_en: 'Chrysanthemum',
    scientific_name: 'Chrysanthemum morifolium',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.EAST, Direction.NE],
    element: Element.AIR,
    sunlight: Sunlight.MEDIUM,
    benefits: ['සතුට සහ සිනහව ගෙන එයි', 'වාතය පිරිසිදු කිරීමට උපකාරී වේ', 'අලංකාර වර්ණ රාශියක්'],
    cautions: ['සතුන්ට විෂ සහිත විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1YAbJp2kF-2vO77cZwCwR8-C7kXpTZkPY'
    ],
    image_search_links: ['https://www.google.com/search?q=Chrysanthemum+plant'],
  },
  {
    plant_id: 'p_coconut',
    order_index: 20,
    name_si: 'පොල් (Coconut)',
    name_en: 'Coconut',
    scientific_name: 'Cocos nucifera',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.NORTH, Direction.EAST],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['පූජනීය ශාකයකි', 'සෞභාග්‍යයේ සංකේතය', 'සෑම කොටසක්ම ප්‍රයෝජනවත් වේ'],
    cautions: ['වැටෙන පොල් ගෙඩි ගැන අවධානයෙන් සිටින්න'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1f3K9A6Y7QsZZ-EOhq54d1DwIykp5I_De'
    ],
    image_search_links: ['https://www.google.com/search?q=Coconut+tree+Vastu'],
  },
  {
    plant_id: 'p_cosmos',
    order_index: 21,
    name_si: 'කොස්මොස් (Cosmos)',
    name_en: 'Cosmos',
    scientific_name: 'Cosmos bipinnatus',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.WEST, Direction.NW],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['සමනලුන් සහ මී මැස්සන් ආකර්ෂණය කරයි', 'සරල සහ ලස්සන මල්', 'ධනාත්මක ශක්තිය'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1oqj8exnBjfqaXLcmK_W80haxrpc43VF5'
    ],
    image_search_links: ['https://www.google.com/search?q=Cosmos+flower+plant'],
  },
  {
    plant_id: 'p_croton',
    order_index: 22,
    name_si: 'ක්‍රෝටන් (Croton)',
    name_en: 'Croton',
    scientific_name: 'Codiaeum variegatum',
    category: [Category.OUTDOOR],
    directions: [Direction.EAST, Direction.SE],
    element: Element.FIRE,
    sunlight: Sunlight.FULL,
    benefits: ['වර්ණවත් පත්‍ර රටා', 'උද්‍යානයට දීප්තියක් එක් කරයි', 'අඩු නඩත්තුව'],
    cautions: ['කිරි විෂ සහිත විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: [
      'https://lh3.googleusercontent.com/d/1DoNu_aEapVWrisKlHLVdFry-4uqRtpsv'
    ],
    image_search_links: ['https://www.google.com/search?q=Croton+plant+varieties'],
  },
  {
    plant_id: 'p_curry_leaves',
    order_index: 23,
    name_si: 'කරපිංචා (Curry Leaves)',
    name_en: 'Curry Leaves',
    scientific_name: 'Murraya koenigii',
    category: [Category.OUTDOOR, Category.HERB],
    directions: [Direction.NW, Direction.SE],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['ඖෂධීය ශාකයකි', 'ආහාර රසවත් කරයි', 'ධනාත්මක සුවඳක්'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1l7Jx6d7Lt3tZ87IiAF0TTnEvK3GmVXJy'
    ],
    image_search_links: ['https://www.google.com/search?q=Murraya+koenigii+tree'],
  },
  {
    plant_id: 'p_custard_apple',
    order_index: 24,
    name_si: 'අනෝදා (Custard Apple)',
    name_en: 'Custard Apple',
    scientific_name: 'Annona squamosa',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['පෝෂ්‍යදායී පලතුරකි', 'සෞඛ්‍ය සම්පන්නයි', 'හොඳ සෙවණක්'],
    cautions: ['ඇට විෂ සහිතයි, දරුවන්ගෙන් ප්‍රවේශම් වන්න'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/13h1JyVNh0MdAJCSyAjHmLEHMa2AS1xoH'
    ],
    image_search_links: ['https://www.google.com/search?q=Custard+Apple+tree'],
  },
  {
    plant_id: 'p_cyclamen',
    order_index: 25,
    name_si: 'සයික්ලමන් (Cyclamen)',
    name_en: 'Cyclamen',
    scientific_name: 'Cyclamen persicum',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.WATER,
    sunlight: Sunlight.LOW,
    benefits: ['ආදරය සහ භක්තිය සංකේතවත් කරයි', 'හෘද හැඩැති පත්‍ර', 'ශීත ඍතුවේ මල් පිපීම'],
    cautions: ['බල්බය විෂ සහිතයි'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: [
      'https://lh3.googleusercontent.com/d/1bwAlel_aERhvIBJhK2lrd7h--bVvBlNN'
    ],
    image_search_links: ['https://www.google.com/search?q=Cyclamen+plant'],
  },
  {
    plant_id: 'p_dahlia',
    order_index: 26,
    name_si: 'ඩේලියා (Dahlia)',
    name_en: 'Dahlia',
    scientific_name: 'Dahlia hortensis',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.NORTH],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['වර්ණවත් සහ විශාල මල්', 'උද්‍යානයට සජීවී බවක් එක් කරයි', 'ධනාත්මක ශක්තිය'],
    cautions: ['සතුන් විසින් ආහාරයට ගත්තොත් මඳක් විෂ විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1FDMdLHISrE2ILSfflWETk6gdG6AWI1Pu'
    ],
    image_search_links: ['https://www.google.com/search?q=Dahlia+flower+plant'],
  },
  {
    plant_id: 'p_dracaena',
    order_index: 27,
    name_si: 'ඩ්‍රැසීනා (Dracaena)',
    name_en: 'Dracaena',
    scientific_name: 'Dracaena marginata',
    category: [Category.INDOOR],
    directions: [Direction.EAST, Direction.NE],
    element: Element.AIR,
    sunlight: Sunlight.MEDIUM,
    benefits: ['වාතය පිරිසිදු කරයි', 'අඩු නඩත්තුව', 'වාසනාවන්ත ශාකයකි'],
    cautions: ['සතුන්ට විෂ සහිත විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1hTGbMfFrf2C--SMexHGtz4Q8CR-aURTs'
    ],
    image_search_links: ['https://www.google.com/search?q=Dracaena+plant'],
  },
  {
    plant_id: 'p_dragon_fruit',
    order_index: 28,
    name_si: 'ඩ්‍රැගන් ෆෘට් (Dragon Fruit)',
    name_en: 'Dragon Fruit',
    scientific_name: 'Selenicereus undatus',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.WEST, Direction.NW],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['ගුණදායක පලතුරකි', 'නියඟයට ඔරොත්තු දෙයි', 'අලංකාර රාත්‍රී මල්'],
    cautions: ['කටු ඇති බැවින් ප්‍රවේශම් වන්න'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1UF4EQP5xxwHKWFw8MjTDKtyVOqT9JJNH'
    ],
    image_search_links: ['https://www.google.com/search?q=Dragon+Fruit+plant'],
  },
  {
    plant_id: 'p_drumstick',
    order_index: 29,
    name_si: 'මුරුංගා (Drumstick)',
    name_en: 'Drumstick / Moringa',
    scientific_name: 'Moringa oleifera',
    category: [Category.OUTDOOR, Category.HERB, Category.FRUIT],
    directions: [Direction.NW, Direction.NORTH],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['ඖෂධීය ශාකයකි', 'පෝෂ්‍යදායී කොළ සහ කරල්', 'ප්‍රතිශක්තිය වැඩි කරයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1hvAV-4A_6zQpku83xoXgZEXobptIKcxI'
    ],
    image_search_links: ['https://www.google.com/search?q=Moringa+oleifera+tree'],
  },
  {
    plant_id: 'p_duranta',
    order_index: 30,
    name_si: 'දුරාන්ත / රන් පිනි බින්දු (Duranta)',
    name_en: 'Duranta (Golden Dewdrop)',
    scientific_name: 'Duranta erecta',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.SOUTH, Direction.SE],
    element: Element.FIRE,
    sunlight: Sunlight.FULL,
    benefits: ['වැටවල් සඳහා ඉතා සුදුසුයි', 'සමනලුන් ආකර්ෂණය කරයි', 'අලංකාර කහ ගෙඩි'],
    cautions: ['ගෙඩි සහ පත්‍ර විෂ සහිතයි'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: [
      'https://lh3.googleusercontent.com/d/1WUtnX0fzZ1h3juGXuXVZs-5kmLWLi-kh'
    ],
    image_search_links: ['https://www.google.com/search?q=Duranta+erecta+plant'],
  },
  {
    plant_id: 'p_durian',
    order_index: 31,
    name_si: 'දුරියන් (Durian)',
    name_en: 'Durian',
    scientific_name: 'Durio zibethinus',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SW],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['පලතුරුවල රජු', 'හොඳ සෙවණක් ලබා දෙයි', 'විශාල ශක්තියක් ගෙන එයි'],
    cautions: ['වැටෙන කටු සහිත ගෙඩි ගැන සැලකිලිමත් වන්න'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/15YEeiNi4fkfAHdRVuMpUsEhqWDN2fqL3'
    ],
    image_search_links: ['https://www.google.com/search?q=Durian+tree'],
  },
  {
    plant_id: 'p_english_ivy',
    order_index: 32,
    name_si: 'ඉංග්‍රීසි අයිවි (English Ivy)',
    name_en: 'English Ivy',
    scientific_name: 'Hedera helix',
    category: [Category.INDOOR],
    directions: [Direction.NORTH, Direction.NW],
    element: Element.AIR,
    sunlight: Sunlight.LOW,
    benefits: ['වාතයේ පුස් ඉවත් කරයි', 'හොඳින් පැතිරෙන වැලකි', 'වාතය පිරිසිදු කරයි'],
    cautions: ['මිනිසුන්ට සහ සතුන්ට විෂ සහිත විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: [
      'https://lh3.googleusercontent.com/d/1kpiTgnqrtcBfR47vLxBfC2fQ0rX1WqJ3'
    ],
    image_search_links: ['https://www.google.com/search?q=English+Ivy+plant'],
  },
  {
    plant_id: 'p_fan_palm',
    order_index: 33,
    name_si: 'විසිරුණු පාම් (Fan Palm)',
    name_en: 'Fan Palm',
    category: [Category.OUTDOOR, Category.INDOOR],
    directions: [Direction.NORTH, Direction.NW],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['වාතය පිරිසිදු කරයි', 'අලංකාර පෙනුමක් ලබා දෙයි', 'ධනාත්මක ශක්තිය කැඳවයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1EjnW-QrVFH4e1b2tHdqezsui-6GhBn5j'],
    image_search_links: ['https://www.google.com/search?q=Fan+Palm+plant'],
  },
  {
    plant_id: 'p_ficus_racemosa',
    order_index: 34,
    name_si: 'අත්තික්කා (Attikka)',
    name_en: 'Ficus racemosa',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['පූජනීය ශාකයකි', 'ඖෂධීය ගුණ රාශියක් ඇත', 'සොබාදහම රැකීමට උපකාරී වේ'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1fQe-lxA5A07oHCjpAuC1veqE_RxMgIzO'],
    image_search_links: ['https://www.google.com/search?q=Ficus+racemosa+tree'],
  },
  {
    plant_id: 'p_foxtail_palm',
    order_index: 35,
    name_si: 'ෆොක්ස්ටේල් පාම් (Foxtail Palm)',
    name_en: 'Foxtail Palm',
    category: [Category.OUTDOOR],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['ඉතා අලංකාර විසිතුරු ශාකයකි', 'ගෙවත්තට පිරිපුන් පෙනුමක් ලබා දෙයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1C02aSe6loLrulKVi0I-tbdxNmxYzQiBp'],
    image_search_links: ['https://www.google.com/search?q=Foxtail+Palm+tree'],
  },
  {
    plant_id: 'p_frangipani',
    order_index: 36,
    name_si: 'අරලිය (Araliya)',
    name_en: 'Frangipani / Plumeria',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.NORTH, Direction.NE, Direction.SW],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['සුවඳවත් මල්', 'සන්සුන් බවක් ලබා දෙයි', 'පූජනීය ස්ථාන වල බහුලව දක්නට ලැබේ'],
    cautions: ['කිරි ඇසට හෝ සමට අහිතකර විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1tU6rhyNMgDAoD2ZRdGlYJpk18fyI82Xu',
      'https://lh3.googleusercontent.com/d/1rNBljGQ_cFCNPpG-7DTe6q_Xx2F0DQWh'
    ],
    image_search_links: ['https://www.google.com/search?q=Plumeria+Frangipani+tree'],
  },
  {
    plant_id: 'p_gardenia_v2',
    order_index: 37,
    name_si: 'ගාඩේනියා (Gardenia)',
    name_en: 'Gardenia',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['ඉතා සුවඳවත් මල්', 'ධනාත්මක ශක්තිය ආකර්ෂණය කරයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1CGKw6YDCGGW4xnii__VrREH4zZyeOSmB'],
    image_search_links: ['https://www.google.com/search?q=Gardenia+jasminoides+plant'],
  },
  {
    plant_id: 'p_geranium',
    order_index: 38,
    name_si: 'ජෙරානියම් (Geranium)',
    name_en: 'Geranium',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.SOUTH, Direction.SE],
    element: Element.FIRE,
    sunlight: Sunlight.MEDIUM,
    benefits: ['වර්ණවත් මල්', 'මදුරුවන් පලවා හැරීමට උපකාරී වේ', 'සතුට කැඳවයි'],
    cautions: ['සතුන්ට මඳක් විෂ සහිත විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1b3DIj_54pMnqBFekt13DNciYCwRl8XdP'],
    image_search_links: ['https://www.google.com/search?q=Geranium+plant'],
  },
  {
    plant_id: 'p_gerbera',
    order_index: 39,
    name_si: 'ජර්බෙරා (Gerbera)',
    name_en: 'Gerbera',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.EAST, Direction.NORTH],
    element: Element.WATER,
    sunlight: Sunlight.MEDIUM,
    benefits: ['දීප්තිමත් මල්', 'රාත්‍රියේ ඔක්සිජන් මුදා හරියි', 'මානසික ආතතිය අඩු කරයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1WTuleQqXCnQ_N1wbMN6X1HZmMC_at-OV'],
    image_search_links: ['https://www.google.com/search?q=Gerbera+Daisy+plant'],
  },
  {
    plant_id: 'p_gladiolus',
    order_index: 40,
    name_si: 'ග්ලැඩියෝලස් (Gladiolus)',
    name_en: 'Gladiolus',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.EAST, Direction.NE],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['ශක්තිය සහ අඛණ්ඩතාව සංකේතවත් කරයි', 'අලංකාර මල් දඬු'],
    cautions: [],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1LNz37PnhURGOWA9mDBxFrCphtLDhAjOG'],
    image_search_links: ['https://www.google.com/search?q=Gladiolus+flower+plant'],
  },
  {
    plant_id: 'p_gloxinia',
    order_index: 41,
    name_si: 'ග්ලොක්සීනියා (Gloxinia)',
    name_en: 'Gloxinia',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.WATER,
    sunlight: Sunlight.LOW,
    benefits: ['ඉතා ආකර්ෂණීය වෙල්වට් මල්', 'සන්සුන් බවක් ලබා දෙයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1t31nGGfl0RB_NSd-GDRE69mdbBtfayli'],
    image_search_links: ['https://www.google.com/search?q=Gloxinia+plant'],
  },
  {
    plant_id: 'p_grapefruit',
    order_index: 42,
    name_si: 'ග්‍රේප්ෆෘට් (Grapefruit)',
    name_en: 'Grapefruit',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.WEST, Direction.NW],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['පෝෂ්‍යදායී පලතුරකි', 'ප්‍රබෝධමත් සුවඳක් ඇති කරයි'],
    cautions: [],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1nbnlGV3Igr7wvPUbq0XqKSQwnIwjUXeh'],
    image_search_links: ['https://www.google.com/search?q=Grapefruit+tree'],
  },
  {
    plant_id: 'p_guava',
    order_index: 43,
    name_si: 'පේර (Pera)',
    name_en: 'Guava',
    scientific_name: 'Psidium guajava',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.NORTH, Direction.NW],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['ගුණදායක පලතුරු', 'සුවිශේෂී ඖෂධීය ගුණ', 'වටිනා සෙවණක් ලබා දෙයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1a5_YpkTEr1kzpSi23KqwscRsWr8k-d2m'],
    image_search_links: ['https://www.google.com/search?q=Psidium+guajava+tree'],
  },
  {
    plant_id: 'p_heliconia',
    order_index: 44,
    name_si: 'හෙලිකෝනියා (Heliconia)',
    name_en: 'Heliconia',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.SOUTH, Direction.SE],
    element: Element.FIRE,
    sunlight: Sunlight.FULL,
    benefits: ['සුවිශේෂී වර්ණවත් පෙනුම', 'ගෙවත්තට උණුසුම් බවක් එක් කරයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1fgtJoYBb_DPH_lzCwkWp_SuNh1gYlD4R'],
    image_search_links: ['https://www.google.com/search?q=Heliconia+plant'],
  },
  {
    plant_id: 'p_hibiscus',
    order_index: 45,
    name_si: 'වද (Wada)',
    name_en: 'Hibiscus',
    scientific_name: 'Hibiscus rosa-sinensis',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.SOUTH, Direction.SE],
    element: Element.FIRE,
    sunlight: Sunlight.FULL,
    benefits: ['ඖෂධීය ගුණ රාශියක් ඇත', 'ධනාත්මක ශක්තිය පතුරුවයි', 'ආගමික කටයුතු සඳහා යොදා ගනී'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1ScbFVOpte9XYv1IrrfttqNB_SPB4uE1J'],
    image_search_links: ['https://www.google.com/search?q=Hibiscus+rosa-sinensis+plant'],
  },
  {
    plant_id: 'p_hydrangea',
    order_index: 46,
    name_si: 'හයිඩ්‍රැන්ජියා (Hydrangea)',
    name_en: 'Hydrangea',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.WATER,
    sunlight: Sunlight.MEDIUM,
    benefits: ['කැකුළු පිරි මල් ගොමු', 'සමෘද්ධිය සංකේතවත් කරයි'],
    cautions: ['සතුන්ට විෂ සහිතයි'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1ZWe-omkGouDyNK4QItBhcIh56-0stZ5D'],
    image_search_links: ['https://www.google.com/search?q=Hydrangea+plant'],
  },
  {
    plant_id: 'p_ixora',
    order_index: 47,
    name_si: 'රත්මල් (Ratmal)',
    name_en: 'Ixora',
    scientific_name: 'Ixora coccinea',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.EAST, Direction.SE],
    element: Element.FIRE,
    sunlight: Sunlight.FULL,
    benefits: ['පූජනීය ශාකයකි', 'ගෙවත්තට ශක්තියක් ලබා දෙයි', 'වසර පුරා මල් ලබා දෙයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1kHnn3J0IZxj63fU6VNiuz3nkEb9um1oq'],
    image_search_links: ['https://www.google.com/search?q=Ixora+coccinea+plant'],
  },
  {
    plant_id: 'p_ixora_bush',
    order_index: 48,
    name_si: 'රත්මල් පඳුර (Ixora Bush)',
    name_en: 'Ixora Bush',
    category: [Category.OUTDOOR],
    directions: [Direction.EAST, Direction.NE],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['වැටවල් සඳහා සුදුසුයි', 'අඩු නඩත්තුව'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1Kzs09cIiGZ2eTUZfgtzy2P8VktNvxnnC'],
    image_search_links: ['https://www.google.com/search?q=Ixora+hedge+bush'],
  },
  {
    plant_id: 'p_jackfruit',
    order_index: 49,
    name_si: 'කොස් (Kos)',
    name_en: 'Jackfruit',
    scientific_name: 'Artocarpus heterophyllus',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SW, Direction.SOUTH, Direction.WEST],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['"බත් ගස" ලෙස හැඳින්වේ', 'ස්ථාවරත්වය සහ සෞභාග්‍යය කැඳවයි', 'ඉතා පෝෂ්‍යදායී ආහාරයකි'],
    cautions: ['වැටෙන විශාල ගෙඩි ගැන සැලකිලිමත් වන්න'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1TPNdH0s6wnf-ba54U5XE90CoJN69EwBF'],
    image_search_links: ['https://www.google.com/search?q=Artocarpus+heterophyllus+tree'],
  },
  {
    plant_id: 'p_jamun',
    order_index: 50,
    name_si: 'මදං (Madan)',
    name_en: 'Jamun / Java Plum',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SOUTH, Direction.SW],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['ඖෂධීය ගුණ සහිත පලතුරකි', 'විශාල සෙවණක් ලබා දෙයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/15zhpsv7nuZg28-bnztoMsn1cw7YRESs_'],
    image_search_links: ['https://www.google.com/search?q=Jamun+tree+Syzygium+cumini'],
  },
  {
    plant_id: 'p_jasmine',
    order_index: 51,
    name_si: 'සමන් පිච්ච (Jasmine)',
    name_en: 'Jasmine',
    scientific_name: 'Jasminum sambac',
    category: [Category.OUTDOOR, Category.FLOWER, Category.HERB],
    directions: [Direction.NORTH, Direction.NE, Direction.EAST],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['පාරිශුද්ධත්වය සංකේතවත් කරයි', 'ධනාත්මක ශක්තිය පතුරුවයි', 'සුවඳවත් මල්'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/108Nnif_bcQvbTA3hBzXlsyApJKba72ge'],
    image_search_links: ['https://www.google.com/search?q=Jasminum+sambac+plant'],
  },
  {
    plant_id: 'p_jasmine_potted',
    order_index: 52,
    name_si: 'බඳුන්ගත පිච්ච (Potted Jasmine)',
    name_en: 'Jasmine (potted)',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.EAST],
    element: Element.WATER,
    sunlight: Sunlight.MEDIUM,
    benefits: ['නිවස තුළ සුවඳ සහ සන්සුන් බව පතුරුවයි', 'මානසික සහනය'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1p5j-FTYv_SvRe3qZmRg3WJiNsh9Ptw8P'],
    image_search_links: ['https://www.google.com/search?q=potted+jasmine+indoor'],
  },
  {
    plant_id: 'p_kalanchoe',
    order_index: 53,
    name_si: 'කැලන්චෝ (Kalanchoe)',
    name_en: 'Kalanchoe',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.EAST],
    element: Element.WATER,
    sunlight: Sunlight.MEDIUM,
    benefits: ['වර්ණවත් මල්', 'වාතය පිරිසිදු කරයි', 'ධනාත්මක ශක්තිය'],
    cautions: [],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1n-2Rv4uFpVgRFqI1tM0KebxKIDd-H7HW'],
    image_search_links: ['https://www.google.com/search?q=Kalanchoe+plant'],
  },
  {
    plant_id: 'p_langsat',
    order_index: 54,
    name_si: 'ගැඩුම (Langsat)',
    name_en: 'Langsat',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SW, Direction.SOUTH],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['පෝෂ්‍යදායී පලතුරු', 'හොඳ සෙවණක් ලබා දෙයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1lUnTT7YKcB2eEfjeDety-KklnTDjG3Xj'],
    image_search_links: ['https://www.google.com/search?q=Langsat+fruit+tree'],
  },
  {
    plant_id: 'p_lantana_v2',
    order_index: 55,
    name_si: 'ලැන්ටානා (Lantana)',
    name_en: 'Lantana',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.EAST, Direction.NE],
    element: Element.FIRE,
    sunlight: Sunlight.FULL,
    benefits: ['වර්ණවත් මල්', 'සමනලුන් ආකර්ෂණය කරයි'],
    cautions: ['සතුන්ට විෂ සහිත විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: true,
    image_links: ['https://lh3.googleusercontent.com/d/1KjpCP3ulR8rBgkAeNAyAkPCP6MdOdyOD'],
    image_search_links: ['https://www.google.com/search?q=Lantana+camara+plant'],
  },
  {
    plant_id: 'p_lavender',
    order_index: 56,
    name_si: 'ලැවෙන්ඩර් (Lavender)',
    name_en: 'Lavender',
    category: [Category.INDOOR, Category.HERB],
    directions: [Direction.NW, Direction.NORTH],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['සුව නින්දක් ලබා දෙයි', 'මානසික පීඩනය අඩු කරයි', 'සුවඳවත් මල්'],
    cautions: [],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1gi44hIuKL91JZb5aqdDkRRJWfk5QAA1j'],
    image_search_links: ['https://www.google.com/search?q=Lavandula+plant'],
  },
  {
    plant_id: 'p_lemongrass',
    order_index: 57,
    name_si: 'සේර (Lemongrass)',
    name_en: 'Lemongrass',
    scientific_name: 'Cymbopogon citratus',
    category: [Category.OUTDOOR, Category.HERB],
    directions: [Direction.SE, Direction.NW],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['ඖෂධීය ගුණ වැඩියි', 'මදුරුවන් පලවා හරියි', 'ආහාර රසවත් කරයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1tvlK69m6qmnloj6wX2aA1yQqrK4FV8J4',
      'https://lh3.googleusercontent.com/d/1MrcXYjmoF8dAJ19z1-ZWn6k_pGkqTd6S'
    ],
    image_search_links: ['https://www.google.com/search?q=Cymbopogon+citratus+plant'],
  },
  {
    plant_id: 'p_lime',
    order_index: 58,
    name_si: 'දෙහි / ලෙමන් (Lime)',
    name_en: 'Lime / Lemon',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['සෞභාග්‍යය ගෙන එයි', 'ඖෂධීය පලතුරකි'],
    cautions: ['කටු ඇති බැවින් ප්‍රවේශම් වන්න'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1uZ6aLqv5yGXwMZs01dHc6rrK0ATRSmg3'],
    image_search_links: ['https://www.google.com/search?q=Citrus+lime+tree'],
  },
  {
    plant_id: 'p_lotus',
    order_index: 59,
    name_si: 'නෙළුම් (Lotus)',
    name_en: 'Lotus',
    scientific_name: 'Nelumbo nucifera',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.NORTH, Direction.EAST],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['ඉතා පූජනීය ශාකයකි', 'සෞභාග්‍යය සහ පාරිශුද්ධත්වය සංකේතවත් කරයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/12_fz6r-6Ba66hwcIlzFDBAMN0QHe6Pix'],
    image_search_links: ['https://www.google.com/search?q=Nelumbo+nucifera+Lotus'],
  },
  {
    plant_id: 'p_lychee',
    order_index: 60,
    name_si: 'ලයිචි (Lychee)',
    name_en: 'Lychee',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SW, Direction.SOUTH],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['පෝෂ්‍යදායී පලතුරු', 'ගෙවත්තට අලංකාරයක් එක් කරයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1suYf7dt3Ki5N0kMfyXJzHJuzIx8Lya02'],
    image_search_links: ['https://www.google.com/search?q=Lychee+tree'],
  },
  {
    plant_id: 'p_mango',
    order_index: 61,
    name_si: 'අඹ (Mango)',
    name_en: 'Mango',
    scientific_name: 'Mangifera indica',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SW, Direction.SOUTH, Direction.WEST],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['ස්ථාවරත්වය සහ සෞභාග්‍යය ගෙන එයි', 'පලතුරුවල රජු', 'පූජනීය පත්‍ර'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1BLHsirBvZp11bGW4tqPGoEDx_4SmbkZU'],
    image_search_links: ['https://www.google.com/search?q=Mango+tree+Vastu'],
  },
  {
    plant_id: 'p_mangosteen',
    order_index: 62,
    name_si: 'මැංගුස් (Mangosteen)',
    name_en: 'Mangosteen',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SW, Direction.SOUTH],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['අතිශය ගුණදායක පලතුරකි', 'ප්‍රණීත රසය'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1ID-vHV4AonlUnN6cJd7AGXNPgqP3o4vv'],
    image_search_links: ['https://www.google.com/search?q=Mangosteen+tree'],
  },
  {
    plant_id: 'p_mini_chandni',
    order_index: 63,
    name_si: 'කුඩා වැටකේ (Mini Chandni)',
    name_en: 'Mini Chandni',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.EAST],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['අලංකාර සුදු මල්', 'සන්සුන් බවක් ලබා දෙයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1Ja2q4NVXtioE1iSVmPij5UrzRapYqM5p'],
    image_search_links: ['https://www.google.com/search?q=Mini+Chandni+plant'],
  },
  {
    plant_id: 'p_mini_rose',
    order_index: 64,
    name_si: 'කුඩා රෝස (Mini Rose)',
    name_en: 'Mini Rose (pot)',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.SE, Direction.SOUTH],
    element: Element.FIRE,
    sunlight: Sunlight.MEDIUM,
    benefits: ['ආදරය සහ සතුට කැඳවයි', 'නිවසට අලංකාරයක්'],
    cautions: ['කටු ඇති බැවින් ප්‍රවේශම් වන්න'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1AqZSKL_2Pm6-jS8x5UN46Xo5azr3oyms'],
    image_search_links: ['https://www.google.com/search?q=Potted+mini+rose'],
  },
  {
    plant_id: 'p_mint',
    order_index: 65,
    name_si: 'මින්චි (Mint)',
    name_en: 'Mint',
    scientific_name: 'Mentha',
    category: [Category.INDOOR, Category.HERB],
    directions: [Direction.NW, Direction.NORTH],
    element: Element.AIR,
    sunlight: Sunlight.MEDIUM,
    benefits: ['ප්‍රබෝධමත් සුවඳක්', 'ආහාර රසවත් කරයි', 'ධනාත්මක ශක්තිය'],
    cautions: [],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1tzFXzzPjha9MXcTa5YaL8lsqRR75g6Fr'],
    image_search_links: ['https://www.google.com/search?q=Mint+Mentha+plant'],
  },
  {
    plant_id: 'p_monstera',
    order_index: 66,
    name_si: 'මොන්ස්ටෙරා (Monstera)',
    name_en: 'Monstera deliciosa',
    category: [Category.INDOOR],
    directions: [Direction.NE, Direction.EAST],
    element: Element.AIR,
    sunlight: Sunlight.LOW,
    benefits: ['විලාසිතාමය පෙනුම', 'වාතය පිරිසිදු කරයි'],
    cautions: ['සතුන්ට විෂ සහිතයි'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: ['https://lh3.googleusercontent.com/d/1nj_DW0mH07y1Tm373N5HlCb4SoM9yMuh'],
    image_search_links: ['https://www.google.com/search?q=Monstera+deliciosa+plant'],
  },
  {
    plant_id: 'p_mulberry',
    order_index: 67,
    name_si: 'මල්බෙරි (Mulberry)',
    name_en: 'Mulberry',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.NW, Direction.WEST],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['ගුණදායක පලතුරු', 'ඉක්මනින් වර්ධනය වේ'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1rMRCyGRrpXGIDABYh1WnAey1jbC-3qIJ'],
    image_search_links: ['https://www.google.com/search?q=Mulberry+tree'],
  },
  {
    plant_id: 'p_murraya',
    order_index: 68,
    name_si: 'එටේරිය (Murraya)',
    name_en: 'Murraya (Orange Jasmine)',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.EAST],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['ඉතා සුවඳවත් මල්', 'වැටවල් සඳහා සුදුසුයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1iDWU6yUwbzoGV-NpqIglQeH1PKLAMhR2'],
    image_search_links: ['https://www.google.com/search?q=Murraya+paniculata+plant'],
  },
  {
    plant_id: 'p_neem',
    order_index: 69,
    name_si: 'කොහොඹ (Neem)',
    name_en: 'Neem',
    scientific_name: 'Azadirachta indica',
    category: [Category.OUTDOOR, Category.HERB],
    directions: [Direction.NW, Direction.NORTH],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['ඉහළම ඖෂධීය වටිනාකම', 'වාතය පිරිසිදු කිරීමේ විශේෂ හැකියාව', 'කෘමීන් පලවා හරියි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: [
      'https://lh3.googleusercontent.com/d/1Fp-4cjZufaheMCJyaAP9Ja4t-UomjA1R',
      'https://lh3.googleusercontent.com/d/1ZeamtfzQGg9IF6UhHCmDV0kJDw2F1Bcg'
    ],
    image_search_links: ['https://www.google.com/search?q=Neem+tree+Vastu'],
  },
  {
    plant_id: 'p_oleander_v2',
    order_index: 70,
    name_si: 'කණේරු (Oleander)',
    name_en: 'Oleander (toxic)',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.SOUTH, Direction.SE],
    element: Element.FIRE,
    sunlight: Sunlight.FULL,
    benefits: ['අලංකාර මල්'],
    cautions: ['ඉතා විෂ සහිතයි - කුඩා දරුවන් සහ සතුන්ගෙන් ඈත් කර තබන්න'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: ['https://lh3.googleusercontent.com/d/1CpRMC7fdWmAqxIbQNsPO4riU4Fd2IAbP'],
    image_search_links: ['https://www.google.com/search?q=Oleander+toxic+plant'],
  },
  {
    plant_id: 'p_orange',
    order_index: 71,
    name_si: 'දොඩම් (Orange)',
    name_en: 'Orange',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['සතුට සහ සෞභාග්‍යය කැඳවයි', 'පෝෂ්‍යදායී පලතුරකි'],
    cautions: [],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/17TqXVps0gh7GoRpfqNZWSW8XPn0LNr_f'],
    image_search_links: ['https://www.google.com/search?q=Orange+tree'],
  },
  {
    plant_id: 'p_orchids',
    order_index: 72,
    name_si: 'ඕකිඩ් (Orchids)',
    name_en: 'Orchids',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.EAST, Direction.NORTH],
    element: Element.AIR,
    sunlight: Sunlight.MEDIUM,
    benefits: ['ආදරය සහ සශ්‍රීකත්වය සංකේතවත් කරයි', 'අතිශය අලංකාර මල්'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/14Q1uJSZyw2B7cOxpu1QgdVRQwszf6kKA'],
    image_search_links: ['https://www.google.com/search?q=Orchid+flowers'],
  },
  {
    plant_id: 'p_pandan',
    order_index: 73,
    name_si: 'රම්පේ (Pandan)',
    name_en: 'Pandan',
    category: [Category.OUTDOOR, Category.HERB],
    directions: [Direction.NE, Direction.NORTH],
    element: Element.WATER,
    sunlight: Sunlight.MEDIUM,
    benefits: ['සුවඳවත් පත්‍ර', 'ආහාර රසවත් කරයි', 'ඖෂධීය ගුණ'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1cOsfE2DoH9Xr-Dh9e7oT_sQZ1HyIamZY'],
    image_search_links: ['https://www.google.com/search?q=Pandan+plant+ramp-e'],
  },
  {
    plant_id: 'p_papaya',
    order_index: 74,
    name_si: 'ගස්ලබු (Papaya)',
    name_en: 'Papaya',
    scientific_name: 'Carica papaya',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SW, Direction.WEST],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['ඉතා ගුණදායක පලතුරකි', 'ප්‍රතිශක්තිය වැඩි කරයි'],
    cautions: ['නිවසට ඉතා සමීපව වැවීම අසුභ විය හැක'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1ld8nKDZocP76pHVIwhIL0pBRB1wXV3Gk'],
    image_search_links: ['https://www.google.com/search?q=Papaya+tree'],
  },
  {
    plant_id: 'p_passion_fruit',
    order_index: 75,
    name_si: 'පැෂන් ෆෘට් (Passion Fruit)',
    name_en: 'Passion Fruit',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.WEST, Direction.NW],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['ප්‍රණීත පලතුරකි', 'ඉතා ආකර්ෂණීය මල්'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/19RJ3vm1li3UkdK-SY4miQ3yCcWJn5Tzi'],
    image_search_links: ['https://www.google.com/search?q=Passion+fruit+vine'],
  },
  {
    plant_id: 'p_peace_lily',
    order_index: 76,
    name_si: 'පීස් ලිලි (Peace Lily)',
    name_en: 'Peace Lily',
    scientific_name: 'Spathiphyllum',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.NORTH, Direction.EAST],
    element: Element.WATER,
    sunlight: Sunlight.LOW,
    benefits: ['සන්සුන් බව ගෙන එයි', 'වාතය පිරිසිදු කරයි'],
    cautions: ['සතුන්ට සහ දරුවන්ට විෂ සහිතයි'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: ['https://lh3.googleusercontent.com/d/1ShOyZwxA6ndJcwwFGAZxhlYC0kymTUAy'],
    image_search_links: ['https://www.google.com/search?q=Spathiphyllum+Peace+Lily'],
  },
  {
    plant_id: 'p_petunia',
    order_index: 77,
    name_si: 'පෙටුනියා (Petunia)',
    name_en: 'Petunia',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.EAST],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['වර්ණවත් මල් ගොමු', 'සතුට පතුරුවයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1nGiWsiB2-5eP2by8S5TRUDw4c6s9V0o-'],
    image_search_links: ['https://www.google.com/search?q=Petunia+plant'],
  },
  {
    plant_id: 'p_philodendron',
    order_index: 78,
    name_si: 'ෆිලෝඩෙන්ඩ්‍රන් (Philodendron)',
    name_en: 'Philodendron',
    category: [Category.INDOOR],
    directions: [Direction.NE, Direction.EAST],
    element: Element.AIR,
    sunlight: Sunlight.LOW,
    benefits: ['වාතය පිරිසිදු කරයි', 'අලංකාර පත්‍ර රටා'],
    cautions: ['සතුන්ට විෂ සහිතයි'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: ['https://lh3.googleusercontent.com/d/164LqZAS6mHGJaf-LuF-WDNFAq22HxjFE'],
    image_search_links: ['https://www.google.com/search?q=Philodendron+plant'],
  },
  {
    plant_id: 'p_zz_plant',
    order_index: 79,
    name_si: 'ජේඩ් වැනි ශාකය (ZZ Plant)',
    name_en: 'ZZ Plant',
    category: [Category.INDOOR],
    directions: [Direction.SE, Direction.SOUTH, Direction.EAST],
    element: Element.EARTH,
    sunlight: Sunlight.LOW,
    benefits: ['සෞභාග්‍යය ගෙන එයි', 'අඩු නඩත්තුව', 'වාතය පිරිසිදු කරයි'],
    cautions: ['සිරුරට විෂ සහිතයි'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: [
      'https://lh3.googleusercontent.com/d/1vHPOAxKp9pyaYmCaCVJ8iJsnOFxfjADw',
      'https://lh3.googleusercontent.com/d/1to3cULKUXw9_eo6g5CwhJ6axKKzFDPnv'
    ],
    image_search_links: ['https://www.google.com/search?q=ZZ+Plant+Zamioculcas'],
  },
  {
    plant_id: 'p_plumbago',
    order_index: 80,
    name_si: 'ප්ලම්බගෝ (Plumbago)',
    name_en: 'Plumbago',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.NORTH],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['අලංකාර නිල් මල්', 'වැටවල් සඳහා සුදුසුයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1gOcAsCk62Dh_9PG-7ZJjnU3l9V1Y5XA3'],
    image_search_links: ['https://www.google.com/search?q=Plumbago+plant'],
  },
  {
    plant_id: 'p_poinsettia',
    order_index: 81,
    name_si: 'පොයින්සෙටියා (Poinsettia)',
    name_en: 'Poinsettia',
    category: [Category.INDOOR, Category.FLOWER],
    directions: [Direction.SE, Direction.SOUTH],
    element: Element.FIRE,
    sunlight: Sunlight.MEDIUM,
    benefits: ['වර්ණවත් පෙනුම', 'සතුට ගෙන එයි'],
    cautions: ['කිරි විෂ සහිත විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: ['https://lh3.googleusercontent.com/d/1jMCtnGbKhXd-jqoR5YM-z5qAZZY2JzX-'],
    image_search_links: ['https://www.google.com/search?q=Poinsettia+plant'],
  },
  {
    plant_id: 'p_pomegranate',
    order_index: 82,
    name_si: 'දෙළුම් (Pomegranate)',
    name_en: 'Pomegranate',
    scientific_name: 'Punica granatum',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.NORTH, Direction.NE, Direction.EAST],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['ඉතා ගුණදායක පලතුරකි', 'සෞභාග්‍යයේ සංකේතය'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1oo8wRhLnpfSpm-GFcIXRWYAVDUJWnZMC'],
    image_search_links: ['https://www.google.com/search?q=Pomegranate+tree+Vastu'],
  },
  {
    plant_id: 'p_portulaca',
    order_index: 83,
    name_si: 'මොස් රෝස් (Portulaca)',
    name_en: 'Portulaca / Moss Rose',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.SE, Direction.SOUTH],
    element: Element.FIRE,
    sunlight: Sunlight.FULL,
    benefits: ['වර්ණවත් මල් පලසක් මෙන් පැතිරේ', 'අඩු නඩත්තුව'],
    cautions: [],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1YGwp6MY7hXgWL21_3-gOMmZ3Ygqn7gN8'],
    image_search_links: ['https://www.google.com/search?q=Portulaca+Moss+Rose'],
  },
  {
    plant_id: 'p_rambutan',
    order_index: 84,
    name_si: 'රඹුටන් (Rambutan)',
    name_en: 'Rambutan',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SW, Direction.SOUTH],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['පෝෂ්‍යදායී පලතුරු', 'ආර්ථික වටිනාකම'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1evO-bAyesZ6THQB9hupSR2RElqmbwiXs'],
    image_search_links: ['https://www.google.com/search?q=Rambutan+tree'],
  },
  {
    plant_id: 'p_rose_apple',
    order_index: 85,
    name_si: 'ජම්බු (Jambu)',
    name_en: 'Rose Apple',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SW, Direction.SOUTH],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['ප්‍රණීත පලතුරකි', 'ප්‍රබෝධමත් සෙවණක් ලබා දෙයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1rj1JeDTixsraObiLmJbC5FmI-J730jY5'],
    image_search_links: ['https://www.google.com/search?q=Rose+apple+tree+Syzygium'],
  },
  {
    plant_id: 'p_rose',
    order_index: 86,
    name_si: 'රෝස (Rose)',
    name_en: 'Rose',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.SOUTH, Direction.SE],
    element: Element.FIRE,
    sunlight: Sunlight.FULL,
    benefits: ['ආදරය සහ සතුට ගෙන එයි', 'සුවඳවත් මල්'],
    cautions: ['කටු ඇති බැවින් ප්‍රවේශම් වන්න'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1zBMlZbmvhsFhXyxm6uR0cARjn-Y0XbWy'],
    image_search_links: ['https://www.google.com/search?q=Rose+bush+plant'],
  },
  {
    plant_id: 'p_rubber_plant',
    order_index: 87,
    name_si: 'රබර් (Rubber Plant)',
    name_en: 'Rubber Plant (Ficus elastica)',
    category: [Category.INDOOR, Category.OUTDOOR],
    directions: [Direction.NW, Direction.WEST],
    element: Element.AIR,
    sunlight: Sunlight.MEDIUM,
    benefits: ['වාතය පිරිසිදු කරයි', 'අලංකාර පත්‍ර රටා'],
    cautions: ['කිරි විෂ සහිතයි - කුඩා දරුවන්ගෙන් සහ සතුන්ගෙන් ඈත් කරන්න'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: ['https://lh3.googleusercontent.com/d/1RYCa1Hx5iCX05rO_HdIYRHOY0tnX44cd'],
    image_search_links: ['https://www.google.com/search?q=Ficus+elastica+Rubber+plant'],
  },
  {
    plant_id: 'p_sago_palm',
    order_index: 88,
    name_si: 'සාගෝ පාම් (Sago Palm)',
    name_en: 'Sago Palm',
    category: [Category.OUTDOOR, Category.INDOOR],
    directions: [Direction.SW, Direction.SOUTH],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['අලංකාර පෙනුමක් ලබා දෙයි', 'ස්ථාවර බව සංකේතවත් කරයි'],
    cautions: ['ඉතා විෂ සහිතයි - සුරතල් සතුන්ට මාරාන්තික විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.NO,
    avoid_if_kids_pets: true,
    image_links: ['https://lh3.googleusercontent.com/d/1PiBC4ercVSX0eCoOC5UkvdDhBm4MPDs2'],
    image_search_links: ['https://www.google.com/search?q=Sago+Palm+Cycas+revoluta'],
  },
  {
    plant_id: 'p_snake_plant_zeylanica',
    order_index: 89,
    name_si: 'ස්නේක් ප්ලාන්ට් (Zeylanica)',
    name_en: 'Sansevieria zeylanica',
    category: [Category.INDOOR],
    directions: [Direction.NE, Direction.NORTH],
    element: Element.WATER,
    sunlight: Sunlight.LOW,
    benefits: ['රාත්‍රියේ ඔක්සිජන් පිට කරයි', 'වාතය පිරිසිදු කරයි', 'අඩු නඩත්තුව'],
    cautions: ['මඳක් විෂ සහිත විය හැක'],
    pet_safe: SafetyStatus.NO,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1whBOB_SrnzeHuXXLYRvbQ_8gGdhQnT_8'],
    image_search_links: ['https://www.google.com/search?q=Sansevieria+zeylanica+plant'],
  },
  {
    plant_id: 'p_sapodilla',
    order_index: 90,
    name_si: 'සැපඩිල්ලා (Sapodilla)',
    name_en: 'Sapodilla (Chikoo)',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SW, Direction.SOUTH],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['ඉතා රසවත් පලතුරකි', 'හොඳ සෙවණක් ලබා දෙයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1X-7kQ9nZPyAO80pcy3XKnJC3hWnlrN8Z'],
    image_search_links: ['https://www.google.com/search?q=Sapodilla+fruit+tree'],
  },
  {
    plant_id: 'p_soursop',
    order_index: 91,
    name_si: 'කටු අනෝදා (Katu Anoda)',
    name_en: 'Soursop (Graviola)',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.NORTH, Direction.NE],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['පිළිකා නාශක ගුණ සහිතයි', 'ඉතා ගුණදායක පලතුරකි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/13oosXVRs7KzubweBSt15j-kOazgNaa4K'],
    image_search_links: ['https://www.google.com/search?q=Soursop+tree+Annona+muricata'],
  },
  {
    plant_id: 'p_amberella',
    order_index: 92,
    name_si: 'ඇඹරැල්ලා (Amberella)',
    name_en: 'Spondias Dulcis',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.WEST, Direction.NW],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['ඖෂධීය පලතුරකි', 'වේගයෙන් වර්ධනය වේ'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1z-EYGd4Lytii3yjBS33VwQzTPpl5MMJg'],
    image_search_links: ['https://www.google.com/search?q=Spondias+dulcis+tree'],
  },
  {
    plant_id: 'p_star_fruit',
    order_index: 93,
    name_si: 'කාමරංගා (Kamaranga)',
    name_en: 'Star Fruit',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.WEST, Direction.NW],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['අලංකාර පලතුරු', 'ගෙවත්තට අමුතු පෙනුමක් ලබා දෙයි'],
    cautions: ['වකුගඩු රෝගීන්ට අහිතකර විය හැක'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1kJ-jlKdSxb0qkOj3zrwFx6C_nY3mUS5t'],
    image_search_links: ['https://www.google.com/search?q=Star+fruit+tree+Averrhoa+carambola'],
  },
  {
    plant_id: 'p_sunflower',
    order_index: 94,
    name_si: 'සූරියකාන්ත (Sunflower)',
    name_en: 'Sunflower',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.EAST],
    element: Element.FIRE,
    sunlight: Sunlight.FULL,
    benefits: ['ධනාත්මක ශක්තිය සහ සතුට ගෙන එයි', 'සූර්යයාගේ සංකේතය'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1JJm1PG-knbri6PVObnFuIYNsuLel9kDX'],
    image_search_links: ['https://www.google.com/search?q=Sunflower+plant'],
  },
  {
    plant_id: 'p_wathusudda',
    order_index: 95,
    name_si: 'වතුසුද්ද (Wathusudda)',
    name_en: 'Tabernaemontana',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.NORTH],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['පූජනීය ශාකයකි', 'පාරිශුද්ධත්වය සංකේතවත් කරයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1F0E86vVYvhQbOfz53V00kj6J3zMJjWgN'],
    image_search_links: ['https://www.google.com/search?q=Tabernaemontana+divaricata+plant'],
  },
  {
    plant_id: 'p_tamarind',
    order_index: 96,
    name_si: 'සියඹලා (Siyambala)',
    name_en: 'Tamarind',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.SOUTH, Direction.SW],
    element: Element.EARTH,
    sunlight: Sunlight.FULL,
    benefits: ['ඖෂධීය සහ ආහාරමය වටිනාකම', 'ඉතා ශක්තිමත් ගසකි'],
    cautions: ['නිවසට ඉතා සමීපව වැවීමෙන් වළකින්න'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/19sUCTWIRT-gioEnX_-3hMTep8MukM5wA'],
    image_search_links: ['https://www.google.com/search?q=Tamarind+tree+Vastu'],
  },
  {
    plant_id: 'p_thuja',
    order_index: 97,
    name_si: 'තූජා (Thuja)',
    name_en: 'Thuja (hedge)',
    category: [Category.OUTDOOR],
    directions: [Direction.NORTH, Direction.NW],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['වැටවල් සඳහා අලංකාර ශාකයකි', 'ධනාත්මක ශක්තිය පතුරුවයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1mke5QblyeliDrfMrEnvmNxsBxkrtwgFa'],
    image_search_links: ['https://www.google.com/search?q=Thuja+orientalis+hedge'],
  },
  {
    plant_id: 'p_travelers_palm',
    order_index: 98,
    name_si: 'පැරඩයිස් පාම් (Traveler’s Palm)',
    name_en: 'Traveler’s Palm (Ravenala)',
    category: [Category.OUTDOOR],
    directions: [Direction.EAST, Direction.NORTH],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['සුවිශේෂී විදුලි පංකා හැඩැති පෙනුම', 'ගෙවත්තට උත්කර්ෂවත් බවක් ලබා දෙයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1Ldr_TNm_JyvgCkJfqlkTPQPVuaqhRg3M'],
    image_search_links: ['https://www.google.com/search?q=Ravenala+madagascariensis+tree'],
  },
  {
    plant_id: 'p_tuberose',
    order_index: 99,
    name_si: 'ටියුබරෝස් (Tuberose)',
    name_en: 'Tuberose',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.NORTH],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['ඉතා සුවඳවත් මල්', 'සන්සුන් බවක් ලබා දෙයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1hemS_aEfYylJksaD9ClrfYC5Ps_nl6rH'],
    image_search_links: ['https://www.google.com/search?q=Tuberose+Polianthes+tuberosa'],
  },
  {
    plant_id: 'p_tulsi',
    order_index: 100,
    name_si: 'තුල්සි (Tulsi)',
    name_en: 'Tulsi / Holy Basil',
    scientific_name: 'Ocimum tenuiflorum',
    category: [Category.OUTDOOR, Category.HERB],
    directions: [Direction.NE, Direction.NORTH, Direction.EAST],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['අතිශය පූජනීය ශාකයකි', 'හොඳම වායු පිරිසිදු කාරකයකි', 'ප්‍රතිශක්තිය වැඩි කරයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1rJ-GQwLUMeIoZqenAm_sFK6AmXfpksr6'],
    image_search_links: ['https://www.google.com/search?q=Ocimum+tenuiflorum+Tulsi+Vastu'],
  },
  {
    plant_id: 'p_water_lily',
    order_index: 101,
    name_si: 'ඕලු (Water Lily)',
    name_en: 'Water Lily / Olu',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.NE, Direction.NORTH],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['පාරිශුද්ධත්වය සංකේතවත් කරයි', 'ධනාත්මක ශක්තිය කැඳවයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1RGDa0FwbpMOYEdOudy4vGHJFeh9Sg4s8'],
    image_search_links: ['https://www.google.com/search?q=Nymphaea+Water+Lily+Olu'],
  },
  {
    plant_id: 'p_wood_apple',
    order_index: 102,
    name_si: 'දිවුල් (Diwul)',
    name_en: 'Wood Apple',
    category: [Category.OUTDOOR, Category.FRUIT],
    directions: [Direction.NW, Direction.WEST],
    element: Element.AIR,
    sunlight: Sunlight.FULL,
    benefits: ['ඉතා ගුණදායක පලතුරකි', 'ශක්තිමත් ගසකි'],
    cautions: ['කටු ඇති බැවින් ප්‍රවේශම් වන්න'],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1S9Ias_vHPvF4Vce-VIzTwh8NYv6nt5Vf'],
    image_search_links: ['https://www.google.com/search?q=Wood+apple+tree+Limonia+acidissima'],
  },
  {
    plant_id: 'p_zinnia',
    order_index: 103,
    name_si: 'සිනියා (Zinnia)',
    name_en: 'Zinnia',
    category: [Category.OUTDOOR, Category.FLOWER],
    directions: [Direction.EAST, Direction.NE],
    element: Element.WATER,
    sunlight: Sunlight.FULL,
    benefits: ['වර්ණවත් මල් ගොමු', 'ධනාත්මක බව පතුරුවයි'],
    cautions: [],
    pet_safe: SafetyStatus.YES,
    kids_safe: SafetyStatus.YES,
    avoid_if_kids_pets: false,
    image_links: ['https://lh3.googleusercontent.com/d/1VofvtvgRlxvwrC4ZjX8fsiOhUJMiIe8F'],
    image_search_links: ['https://www.google.com/search?q=Zinnia+flower+plant'],
  }
];

export const ELEMENT_DIRECTION_GUIDE: GuideSection = {
  title_si: 'මූල ධාතුන් සහ දිශාවන්',
  title_en: 'Five Elements & Directions',
  content: [
    'උතුරු දිශාව (North): පඨවි ධාතුව (Earth)',
    'නැගෙනහිර දිශාව (East): ආපෝ ධාතුව (Water)',
    'දකුණු දිශාව (South): තේජෝ ධාතුව (Fire)',
    'බටහිර දිශාව (West): වායෝ ධාතුව (Air)',
    'ඊසාන (NE): ආපෝ ධාතුව (Water) - පිරිසිදුව තබන්න',
    'ගිනිකොණ (SE): තේජෝ ධාතුව (Fire) - කුළුබඩු පැල හොඳයි',
    'නිරිත (SW): පඨවි ධාතුව (Earth) - ස්ථාවරත්වයට විශාල ගස්',
    'වයඹ (NW): වායෝ ධාතුව (Air) - ඉක්මනින් පිටවන දේවල් සඳහා',
    'මධ්‍ය (Center): ආකාශ (Space) - හිස්ව තබන්න (බ්‍රහ්ම පාදය)'
  ]
};

export const SPECIAL_TIPS_GUIDE: GuideSection = {
  title_si: 'විශේෂ උපදෙස්',
  title_en: 'Special Instructions',
  content: [
    'ප්‍රධාන දොර: ප්‍ර්‍රධාන උළුවස්සට ලම්භකව කිසිදු ගසක් නොතිබිය යුතුය.',
    'සෙවණ: උදෑසන සූර්යාලෝකය වැනසෙන පරිදි විශාල ගස් නිවස ඉදිරිපිට නොවැවිය යුතුය.',
    'පිරිසිදුකම: ගෘහස්ථ ශාකවල පත්‍රවල දූවිලි නොරැඳෙන සේ නිතර පිස දැමිය යුතුය.',
    'වියළි කොටස්: වියළි පත්‍ර සහ මැලවුණු මල් වහාම ඉවත් කළ යුතුය.',
    'කටු සහිත ශාක: රෝස හැර අනෙකුත් kටු සහිත ශාක නිවස තුළ තැබීමෙන් වළකින්න.',
    'කිරි සහිත ශාක: නිවසට ඉතා සමීපව kිරි සහිත ශාක (උදා: වරකා, රබර්) වැවීම අසුභය.'
  ]
};

export const SAFETY_GUIDE: GuideSection = {
  title_si: 'දරුවන් සහ සුරතලුන් සඳහා අනතුරු',
  title_en: 'Safety for Kids & Pets',
  content: [
    'Avoid list: ඩිෆෙන්බැකියා (Dieffenbachia), ෆිලෝඩෙන්ඩ්‍රන් (Philodendron), මුදල් වැල් (Pothos), පීස් ලිලි (Peace Lily), ඔලියැන්ඩර් (Oleander), සාෆෝ පාම් (Sago Palm), කැලේඩියම් (Caladium).',
    'සතුන් සඳහා විෂ: ජේඩ් (Jade) - හෘද ස්පන්දනය අඩාල කරයි, ඉංග්‍රීසි අයිවි (English Ivy) - අක්මාවට අහිතකරයි, ලිලී වර්ග - බළලුන්ගේ වකුගඩු අකර්මන්‍ය කරයි.'
  ],
  tips: [
    'බොහෝ අලංකාර ශාක විෂ සහිත විය හැකි බැවින් කුඩා දරුවන් සිටින විට වඩාත් සැලකිලිමත් වන්න.',
    'Pet-friendly ලෙස සලකනු ලබන්නේ: මුදල් පඳුර, පචිරා මුදල් ගස, බොස්ටන් ෆර්න්.'
  ]
};
